/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReplyQueueRouteImport } from './routes/reply-queue'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InvitesRouteImport } from './routes/invites'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as SenderAddressRouteImport } from './routes/sender.$address'
import { Route as RulesIdRouteImport } from './routes/rules.$id'
import { Route as MMailboxRouteImport } from './routes/m.$mailbox'
import { Route as ComposeNewRouteImport } from './routes/compose.new'
import { Route as ComposeDraftIdRouteImport } from './routes/compose.$draftId'
import { Route as AnalyticsDashboardRouteImport } from './routes/analytics.$dashboard'
import { Route as AccountsKeyRouteImport } from './routes/accounts.$key'
import { Route as MSavedSlugRouteImport } from './routes/m.saved.$slug'
import { Route as MLabelNameRouteImport } from './routes/m.label.$name'
import { Route as MMailboxThreadIdRouteImport } from './routes/m.$mailbox.$threadId'
import { Route as MailInboxRouteImport } from './routes/mail.$accountKey.inbox'
import { Route as MailInboxThreadRouteImport } from './routes/mail.$accountKey.inbox.thread.$threadId'
import { Route as MailArchiveRouteImport } from './routes/mail.$accountKey.archive'
import { Route as MailArchiveThreadRouteImport } from './routes/mail.$accountKey.archive.thread.$threadId'
import { Route as MailLabelRouteImport } from './routes/mail.$accountKey.label.$labelId'
import { Route as MailLabelThreadRouteImport } from './routes/mail.$accountKey.label.$labelId.thread.$threadId'
import { Route as MailSavedRouteImport } from './routes/mail.$accountKey.saved.$slug'
import { Route as MailSavedThreadRouteImport } from './routes/mail.$accountKey.saved.$slug.thread.$threadId'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplyQueueRoute = ReplyQueueRouteImport.update({
  id: '/reply-queue',
  path: '/reply-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesRoute = InvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const SenderAddressRoute = SenderAddressRouteImport.update({
  id: '/sender/$address',
  path: '/sender/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIdRoute = RulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RulesRoute,
} as any)
const MMailboxRoute = MMailboxRouteImport.update({
  id: '/m/$mailbox',
  path: '/m/$mailbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeNewRoute = ComposeNewRouteImport.update({
  id: '/compose/new',
  path: '/compose/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeDraftIdRoute = ComposeDraftIdRouteImport.update({
  id: '/compose/$draftId',
  path: '/compose/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsDashboardRoute = AnalyticsDashboardRouteImport.update({
  id: '/$dashboard',
  path: '/$dashboard',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AccountsKeyRoute = AccountsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => AccountsRoute,
} as any)
const MSavedSlugRoute = MSavedSlugRouteImport.update({
  id: '/m/saved/$slug',
  path: '/m/saved/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MLabelNameRoute = MLabelNameRouteImport.update({
  id: '/m/label/$name',
  path: '/m/label/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const MMailboxThreadIdRoute = MMailboxThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MMailboxRoute,
} as any)
const MailInboxRoute = MailInboxRouteImport.update({
  id: '/mail/$accountKey/inbox',
  path: '/mail/$accountKey/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MailInboxThreadRoute = MailInboxThreadRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => MailInboxRoute,
} as any)
const MailArchiveRoute = MailArchiveRouteImport.update({
  id: '/mail/$accountKey/archive',
  path: '/mail/$accountKey/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const MailArchiveThreadRoute = MailArchiveThreadRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => MailArchiveRoute,
} as any)
const MailLabelRoute = MailLabelRouteImport.update({
  id: '/mail/$accountKey/label/$labelId',
  path: '/mail/$accountKey/label/$labelId',
  getParentRoute: () => rootRouteImport,
} as any)
const MailLabelThreadRoute = MailLabelThreadRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => MailLabelRoute,
} as any)
const MailSavedRoute = MailSavedRouteImport.update({
  id: '/mail/$accountKey/saved/$slug',
  path: '/mail/$accountKey/saved/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MailSavedThreadRoute = MailSavedThreadRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => MailSavedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/deliveries': typeof DeliveriesRoute
  '/dev': typeof DevRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/drafts': typeof DraftsRoute
  '/invites': typeof InvitesRoute
  '/jobs': typeof JobsRoute
  '/onboarding': typeof OnboardingRoute
  '/reply-queue': typeof ReplyQueueRoute
  '/rules': typeof RulesRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/accounts/$key': typeof AccountsKeyRoute
  '/analytics/$dashboard': typeof AnalyticsDashboardRoute
  '/compose/$draftId': typeof ComposeDraftIdRoute
  '/compose/new': typeof ComposeNewRoute
  '/m/$mailbox': typeof MMailboxRouteWithChildren
  '/rules/$id': typeof RulesIdRoute
  '/sender/$address': typeof SenderAddressRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/m/$mailbox/$threadId': typeof MMailboxThreadIdRoute
  '/m/label/$name': typeof MLabelNameRoute
  '/m/saved/$slug': typeof MSavedSlugRoute
  '/mail/$accountKey/inbox': typeof MailInboxRouteWithChildren
  '/mail/$accountKey/inbox/thread/$threadId': typeof MailInboxThreadRoute
  '/mail/$accountKey/archive': typeof MailArchiveRouteWithChildren
  '/mail/$accountKey/archive/thread/$threadId': typeof MailArchiveThreadRoute
  '/mail/$accountKey/label/$labelId': typeof MailLabelRouteWithChildren
  '/mail/$accountKey/label/$labelId/thread/$threadId': typeof MailLabelThreadRoute
  '/mail/$accountKey/saved/$slug': typeof MailSavedRouteWithChildren
  '/mail/$accountKey/saved/$slug/thread/$threadId': typeof MailSavedThreadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/deliveries': typeof DeliveriesRoute
  '/dev': typeof DevRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/drafts': typeof DraftsRoute
  '/invites': typeof InvitesRoute
  '/jobs': typeof JobsRoute
  '/onboarding': typeof OnboardingRoute
  '/reply-queue': typeof ReplyQueueRoute
  '/rules': typeof RulesRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/accounts/$key': typeof AccountsKeyRoute
  '/analytics/$dashboard': typeof AnalyticsDashboardRoute
  '/compose/$draftId': typeof ComposeDraftIdRoute
  '/compose/new': typeof ComposeNewRoute
  '/m/$mailbox': typeof MMailboxRouteWithChildren
  '/rules/$id': typeof RulesIdRoute
  '/sender/$address': typeof SenderAddressRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/m/$mailbox/$threadId': typeof MMailboxThreadIdRoute
  '/m/label/$name': typeof MLabelNameRoute
  '/m/saved/$slug': typeof MSavedSlugRoute
  '/mail/$accountKey/inbox': typeof MailInboxRouteWithChildren
  '/mail/$accountKey/inbox/thread/$threadId': typeof MailInboxThreadRoute
  '/mail/$accountKey/archive': typeof MailArchiveRouteWithChildren
  '/mail/$accountKey/archive/thread/$threadId': typeof MailArchiveThreadRoute
  '/mail/$accountKey/label/$labelId': typeof MailLabelRouteWithChildren
  '/mail/$accountKey/label/$labelId/thread/$threadId': typeof MailLabelThreadRoute
  '/mail/$accountKey/saved/$slug': typeof MailSavedRouteWithChildren
  '/mail/$accountKey/saved/$slug/thread/$threadId': typeof MailSavedThreadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/deliveries': typeof DeliveriesRoute
  '/dev': typeof DevRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/drafts': typeof DraftsRoute
  '/invites': typeof InvitesRoute
  '/jobs': typeof JobsRoute
  '/onboarding': typeof OnboardingRoute
  '/reply-queue': typeof ReplyQueueRoute
  '/rules': typeof RulesRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/accounts/$key': typeof AccountsKeyRoute
  '/analytics/$dashboard': typeof AnalyticsDashboardRoute
  '/compose/$draftId': typeof ComposeDraftIdRoute
  '/compose/new': typeof ComposeNewRoute
  '/m/$mailbox': typeof MMailboxRouteWithChildren
  '/rules/$id': typeof RulesIdRoute
  '/sender/$address': typeof SenderAddressRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/m/$mailbox/$threadId': typeof MMailboxThreadIdRoute
  '/m/label/$name': typeof MLabelNameRoute
  '/m/saved/$slug': typeof MSavedSlugRoute
  '/mail/$accountKey/inbox': typeof MailInboxRouteWithChildren
  '/mail/$accountKey/inbox/thread/$threadId': typeof MailInboxThreadRoute
  '/mail/$accountKey/archive': typeof MailArchiveRouteWithChildren
  '/mail/$accountKey/archive/thread/$threadId': typeof MailArchiveThreadRoute
  '/mail/$accountKey/label/$labelId': typeof MailLabelRouteWithChildren
  '/mail/$accountKey/label/$labelId/thread/$threadId': typeof MailLabelThreadRoute
  '/mail/$accountKey/saved/$slug': typeof MailSavedRouteWithChildren
  '/mail/$accountKey/saved/$slug/thread/$threadId': typeof MailSavedThreadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/activity'
    | '/analytics'
    | '/deliveries'
    | '/dev'
    | '/diagnostics'
    | '/drafts'
    | '/invites'
    | '/jobs'
    | '/onboarding'
    | '/reply-queue'
    | '/rules'
    | '/screener'
    | '/search'
    | '/subscriptions'
    | '/accounts/$key'
    | '/analytics/$dashboard'
    | '/compose/$draftId'
    | '/compose/new'
    | '/m/$mailbox'
    | '/rules/$id'
    | '/sender/$address'
    | '/settings/$section'
    | '/m/$mailbox/$threadId'
    | '/m/label/$name'
    | '/m/saved/$slug'
    | '/mail/$accountKey/inbox'
    | '/mail/$accountKey/inbox/thread/$threadId'
    | '/mail/$accountKey/archive'
    | '/mail/$accountKey/archive/thread/$threadId'
    | '/mail/$accountKey/label/$labelId'
    | '/mail/$accountKey/label/$labelId/thread/$threadId'
    | '/mail/$accountKey/saved/$slug'
    | '/mail/$accountKey/saved/$slug/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/activity'
    | '/analytics'
    | '/deliveries'
    | '/dev'
    | '/diagnostics'
    | '/drafts'
    | '/invites'
    | '/jobs'
    | '/onboarding'
    | '/reply-queue'
    | '/rules'
    | '/screener'
    | '/search'
    | '/subscriptions'
    | '/accounts/$key'
    | '/analytics/$dashboard'
    | '/compose/$draftId'
    | '/compose/new'
    | '/m/$mailbox'
    | '/rules/$id'
    | '/sender/$address'
    | '/settings/$section'
    | '/m/$mailbox/$threadId'
    | '/m/label/$name'
    | '/m/saved/$slug'
    | '/mail/$accountKey/inbox'
    | '/mail/$accountKey/inbox/thread/$threadId'
    | '/mail/$accountKey/archive'
    | '/mail/$accountKey/archive/thread/$threadId'
    | '/mail/$accountKey/label/$labelId'
    | '/mail/$accountKey/label/$labelId/thread/$threadId'
    | '/mail/$accountKey/saved/$slug'
    | '/mail/$accountKey/saved/$slug/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/activity'
    | '/analytics'
    | '/deliveries'
    | '/dev'
    | '/diagnostics'
    | '/drafts'
    | '/invites'
    | '/jobs'
    | '/onboarding'
    | '/reply-queue'
    | '/rules'
    | '/screener'
    | '/search'
    | '/subscriptions'
    | '/accounts/$key'
    | '/analytics/$dashboard'
    | '/compose/$draftId'
    | '/compose/new'
    | '/m/$mailbox'
    | '/rules/$id'
    | '/sender/$address'
    | '/settings/$section'
    | '/m/$mailbox/$threadId'
    | '/m/label/$name'
    | '/m/saved/$slug'
    | '/mail/$accountKey/inbox'
    | '/mail/$accountKey/inbox/thread/$threadId'
    | '/mail/$accountKey/archive'
    | '/mail/$accountKey/archive/thread/$threadId'
    | '/mail/$accountKey/label/$labelId'
    | '/mail/$accountKey/label/$labelId/thread/$threadId'
    | '/mail/$accountKey/saved/$slug'
    | '/mail/$accountKey/saved/$slug/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  DeliveriesRoute: typeof DeliveriesRoute
  DevRoute: typeof DevRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DraftsRoute: typeof DraftsRoute
  InvitesRoute: typeof InvitesRoute
  JobsRoute: typeof JobsRoute
  OnboardingRoute: typeof OnboardingRoute
  ReplyQueueRoute: typeof ReplyQueueRoute
  RulesRoute: typeof RulesRouteWithChildren
  ScreenerRoute: typeof ScreenerRoute
  SearchRoute: typeof SearchRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  ComposeDraftIdRoute: typeof ComposeDraftIdRoute
  ComposeNewRoute: typeof ComposeNewRoute
  MMailboxRoute: typeof MMailboxRouteWithChildren
  SenderAddressRoute: typeof SenderAddressRoute
  SettingsSectionRoute: typeof SettingsSectionRoute
  MLabelNameRoute: typeof MLabelNameRoute
  MSavedSlugRoute: typeof MSavedSlugRoute
  MailInboxRoute: typeof MailInboxRouteWithChildren
  MailArchiveRoute: typeof MailArchiveRouteWithChildren
  MailLabelRoute: typeof MailLabelRouteWithChildren
  MailSavedRoute: typeof MailSavedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reply-queue': {
      id: '/reply-queue'
      path: '/reply-queue'
      fullPath: '/reply-queue'
      preLoaderRoute: typeof ReplyQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites': {
      id: '/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sender/$address': {
      id: '/sender/$address'
      path: '/sender/$address'
      fullPath: '/sender/$address'
      preLoaderRoute: typeof SenderAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$id': {
      id: '/rules/$id'
      path: '/$id'
      fullPath: '/rules/$id'
      preLoaderRoute: typeof RulesIdRouteImport
      parentRoute: typeof RulesRoute
    }
    '/m/$mailbox': {
      id: '/m/$mailbox'
      path: '/m/$mailbox'
      fullPath: '/m/$mailbox'
      preLoaderRoute: typeof MMailboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose/new': {
      id: '/compose/new'
      path: '/compose/new'
      fullPath: '/compose/new'
      preLoaderRoute: typeof ComposeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose/$draftId': {
      id: '/compose/$draftId'
      path: '/compose/$draftId'
      fullPath: '/compose/$draftId'
      preLoaderRoute: typeof ComposeDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/$dashboard': {
      id: '/analytics/$dashboard'
      path: '/$dashboard'
      fullPath: '/analytics/$dashboard'
      preLoaderRoute: typeof AnalyticsDashboardRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/accounts/$key': {
      id: '/accounts/$key'
      path: '/$key'
      fullPath: '/accounts/$key'
      preLoaderRoute: typeof AccountsKeyRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/m/saved/$slug': {
      id: '/m/saved/$slug'
      path: '/m/saved/$slug'
      fullPath: '/m/saved/$slug'
      preLoaderRoute: typeof MSavedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/label/$name': {
      id: '/m/label/$name'
      path: '/m/label/$name'
      fullPath: '/m/label/$name'
      preLoaderRoute: typeof MLabelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$mailbox/$threadId': {
      id: '/m/$mailbox/$threadId'
      path: '/$threadId'
      fullPath: '/m/$mailbox/$threadId'
      preLoaderRoute: typeof MMailboxThreadIdRouteImport
      parentRoute: typeof MMailboxRoute
    }
    '/mail/$accountKey/inbox': {
      id: '/mail/$accountKey/inbox'
      path: '/mail/$accountKey/inbox'
      fullPath: '/mail/$accountKey/inbox'
      preLoaderRoute: typeof MailInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/$accountKey/inbox/thread/$threadId': {
      id: '/mail/$accountKey/inbox/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/mail/$accountKey/inbox/thread/$threadId'
      preLoaderRoute: typeof MailInboxThreadRouteImport
      parentRoute: typeof MailInboxRoute
    }
    '/mail/$accountKey/archive': {
      id: '/mail/$accountKey/archive'
      path: '/mail/$accountKey/archive'
      fullPath: '/mail/$accountKey/archive'
      preLoaderRoute: typeof MailArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/$accountKey/archive/thread/$threadId': {
      id: '/mail/$accountKey/archive/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/mail/$accountKey/archive/thread/$threadId'
      preLoaderRoute: typeof MailArchiveThreadRouteImport
      parentRoute: typeof MailArchiveRoute
    }
    '/mail/$accountKey/label/$labelId': {
      id: '/mail/$accountKey/label/$labelId'
      path: '/mail/$accountKey/label/$labelId'
      fullPath: '/mail/$accountKey/label/$labelId'
      preLoaderRoute: typeof MailLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/$accountKey/label/$labelId/thread/$threadId': {
      id: '/mail/$accountKey/label/$labelId/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/mail/$accountKey/label/$labelId/thread/$threadId'
      preLoaderRoute: typeof MailLabelThreadRouteImport
      parentRoute: typeof MailLabelRoute
    }
    '/mail/$accountKey/saved/$slug': {
      id: '/mail/$accountKey/saved/$slug'
      path: '/mail/$accountKey/saved/$slug'
      fullPath: '/mail/$accountKey/saved/$slug'
      preLoaderRoute: typeof MailSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/$accountKey/saved/$slug/thread/$threadId': {
      id: '/mail/$accountKey/saved/$slug/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/mail/$accountKey/saved/$slug/thread/$threadId'
      preLoaderRoute: typeof MailSavedThreadRouteImport
      parentRoute: typeof MailSavedRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsKeyRoute: typeof AccountsKeyRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsKeyRoute: AccountsKeyRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface AnalyticsRouteChildren {
  AnalyticsDashboardRoute: typeof AnalyticsDashboardRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsDashboardRoute: AnalyticsDashboardRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface RulesRouteChildren {
  RulesIdRoute: typeof RulesIdRoute
}

const RulesRouteChildren: RulesRouteChildren = {
  RulesIdRoute: RulesIdRoute,
}

const RulesRouteWithChildren = RulesRoute._addFileChildren(RulesRouteChildren)

interface MMailboxRouteChildren {
  MMailboxThreadIdRoute: typeof MMailboxThreadIdRoute
}

const MMailboxRouteChildren: MMailboxRouteChildren = {
  MMailboxThreadIdRoute: MMailboxThreadIdRoute,
}

const MMailboxRouteWithChildren = MMailboxRoute._addFileChildren(
  MMailboxRouteChildren,
)

interface MailInboxRouteChildren {
  MailInboxThreadRoute: typeof MailInboxThreadRoute
}

const MailInboxRouteChildren: MailInboxRouteChildren = {
  MailInboxThreadRoute: MailInboxThreadRoute,
}

const MailInboxRouteWithChildren = MailInboxRoute._addFileChildren(
  MailInboxRouteChildren,
)

interface MailArchiveRouteChildren {
  MailArchiveThreadRoute: typeof MailArchiveThreadRoute
}

const MailArchiveRouteChildren: MailArchiveRouteChildren = {
  MailArchiveThreadRoute: MailArchiveThreadRoute,
}

const MailArchiveRouteWithChildren = MailArchiveRoute._addFileChildren(
  MailArchiveRouteChildren,
)

interface MailLabelRouteChildren {
  MailLabelThreadRoute: typeof MailLabelThreadRoute
}

const MailLabelRouteChildren: MailLabelRouteChildren = {
  MailLabelThreadRoute: MailLabelThreadRoute,
}

const MailLabelRouteWithChildren = MailLabelRoute._addFileChildren(
  MailLabelRouteChildren,
)

interface MailSavedRouteChildren {
  MailSavedThreadRoute: typeof MailSavedThreadRoute
}

const MailSavedRouteChildren: MailSavedRouteChildren = {
  MailSavedThreadRoute: MailSavedThreadRoute,
}

const MailSavedRouteWithChildren = MailSavedRoute._addFileChildren(
  MailSavedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  DeliveriesRoute: DeliveriesRoute,
  DevRoute: DevRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DraftsRoute: DraftsRoute,
  InvitesRoute: InvitesRoute,
  JobsRoute: JobsRoute,
  OnboardingRoute: OnboardingRoute,
  ReplyQueueRoute: ReplyQueueRoute,
  RulesRoute: RulesRouteWithChildren,
  ScreenerRoute: ScreenerRoute,
  SearchRoute: SearchRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  ComposeDraftIdRoute: ComposeDraftIdRoute,
  ComposeNewRoute: ComposeNewRoute,
  MMailboxRoute: MMailboxRouteWithChildren,
  SenderAddressRoute: SenderAddressRoute,
  SettingsSectionRoute: SettingsSectionRoute,
  MLabelNameRoute: MLabelNameRoute,
  MSavedSlugRoute: MSavedSlugRoute,
  MailInboxRoute: MailInboxRouteWithChildren,
  MailArchiveRoute: MailArchiveRouteWithChildren,
  MailLabelRoute: MailLabelRouteWithChildren,
  MailSavedRoute: MailSavedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
